# Generated by Django 3.2.8 on 2021-10-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follo_dict',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='repo_dict',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updatenowtime',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
