# Generated by Django 3.2.8 on 2021-10-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_auto_20211018_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses_as_student',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_as_teacher',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default='', max_length=100)),
                ('teacher_list', models.JSONField(default=list)),
                ('student_list', models.JSONField(default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.profile')),
            ],
        ),
    ]
