# Generated by Django 3.2.8 on 2021-10-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0003_auto_20211018_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
