# Generated by Django 3.2.8 on 2021-10-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='student_list',
            new_name='user_list',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courses_as_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courses_as_teacher',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
