# Generated by Django 3.2.8 on 2021-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0005_auto_20211018_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_courses',
            field=models.JSONField(default=list),
        ),
    ]
