# Generated by Django 3.2.8 on 2021-10-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0007_alter_course_user_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('upload', models.FileField(upload_to='media')),
                ('course_code', models.CharField(default='', max_length=100)),
                ('file_nature', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_courses',
        ),
    ]
