# Generated by Django 3.2.8 on 2021-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0008_auto_20211019_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
