# Generated by Django 3.2.8 on 2021-10-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0009_alter_upload_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
