# Generated by Django 3.2.8 on 2021-10-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0011_alter_upload_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='roles',
            field=models.CharField(default='', max_length=100000),
        ),
        migrations.AddField(
            model_name='course',
            name='usernames',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
