# Generated by Django 3.2.8 on 2021-10-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0012_auto_20211020_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='usernames',
            new_name='user_names',
        ),
    ]
