# Generated by Django 3.2.8 on 2021-10-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0013_rename_usernames_course_user_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='course',
            name='user_names',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
