# Generated by Django 3.2.8 on 2021-11-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0014_auto_20211020_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_list',
            field=models.JSONField(default=dict),
        ),
    ]
