# Generated by Django 3.2.8 on 2021-11-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0015_profile_course_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
