# Generated by Django 3.2.8 on 2021-11-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0016_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='upload',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
