# Generated by Django 3.2.8 on 2021-11-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0017_auto_20211120_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
