# Generated by Django 3.2.8 on 2021-11-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0019_uploada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploada',
            old_name='upload',
            new_name='uploada',
        ),
    ]
