# Generated by Django 3.2.8 on 2021-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0021_alter_uploada_uploada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploada',
            name='uploada',
            field=models.FileField(upload_to='media/uploada/<django.db.models.fields.CharField>'),
        ),
    ]
