# Generated by Django 3.2.8 on 2021-11-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0023_alter_uploada_uploada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploada',
            name='file_nature',
        ),
    ]
