# Generated by Django 3.2.8 on 2021-11-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0024_remove_uploada_file_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploada',
            name='weightage',
            field=models.IntegerField(default='100'),
        ),
    ]
