# Generated by Django 3.2.8 on 2021-11-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0026_uploadb_uploadl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploadb',
        ),
    ]
