# Generated by Django 3.2.8 on 2021-11-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0027_delete_uploadb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_whom', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('uploadb', models.FileField(upload_to='media/uploadb')),
                ('course_code', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default='0')),
                ('solution_for', models.CharField(default='', max_length=100)),
                ('submit_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
