# Generated by Django 3.2.8 on 2021-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0028_uploadb'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadb',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uploadb',
            name='grade',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='uploadb',
            name='grade_status',
            field=models.IntegerField(default='0'),
        ),
    ]
