# Generated by Django 3.2.8 on 2021-11-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0029_auto_20211123_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('uploadg', models.FileField(upload_to='media/uploadg')),
            ],
        ),
    ]
