# Generated by Django 3.2.8 on 2021-11-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0030_uploadg'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadb',
            name='weightage',
            field=models.IntegerField(default='100'),
        ),
    ]
