# Generated by Django 3.2.8 on 2021-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0031_uploadb_weightage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TApriviledges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_name', models.CharField(default='', max_length=100)),
                ('course_code', models.CharField(default='', max_length=100)),
                ('enrollment', models.BooleanField(default=False)),
                ('add_assignment', models.BooleanField(default=False)),
                ('grade_assignment', models.BooleanField(default=True)),
            ],
        ),
    ]
