# Generated by Django 3.2.8 on 2021-11-26 18:48

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0033_auto_20211125_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('course_code', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('submit_time', models.DateTimeField()),
            ],
        ),
    ]
