# Generated by Django 3.2.8 on 2021-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0034_uploadv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default='', max_length=100)),
                ('assignment_name', models.CharField(default='', max_length=100)),
                ('mark_list', models.JSONField(default=dict)),
            ],
        ),
    ]
